### ISSUE TITLE
agent-auto-authorization  (AutoAuthorize.zip) to be automated

### ISSUE THREAD

**Issue by aagarwalassetic** [tigase/tc-agent-auto-auth#1]
Hi Team,
I am using AWS ECS for the TeamCity setup with 3 TC agents and 1 TC server.
Installed the plugin "agent-auto-auth" and "Agent Auto Authorize" plugins to automatically authorize the agents but it looks like it is working only when the ECS tasks are down and then agents goes to disconnected and connected again.
But if I refresh the agent server and a new agent task is brought up, it doesn't automatically gets authorized and connected.
Is there any way we can automate this part?
Tried putting "auto_authorize=true" in <TeamCitydir>\context\TeamCity\buildAgent\conf\buildAgent.properties from https://github.com/JetBrains/teamcity-docker-images
but it didn't work.
Can you please advise where can I use the "auto_authorize=true" while creating image?

**Comment by arthef** [comment]
Unfortunately I no longer use TC and no longer maintain the code.
